### ISSUE TITLE
Seems to wrongly detect .js files as yaml?

### ISSUE THREAD

**Issue by larsilus** [skrtheboss/prettier-tools#126]
$ pretty-parallel --check .
ℹ Found 623 files [1.9s]
✖ An error occurred while parsing file '.versionrc.js'!
SyntaxError: All collection items must start at the same column (1:1)
>  1 | const glob = require("glob");
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  2 |
     | ^
>  3 | // default JSON updater will read/write "version" property on top-level of that JSON
     | ^
>  4 |
     | ^
>  5 | const bumpFiles = [
     | ^
>  6 |     // mta.yaml
     | ^
>  7 |     { filename: "mta.yaml", updater: "./tools/yaml-version-updater" },
     | ^
>  8 |     // top-level package files
     | ^
>  9 |     { filename: "package.json", type: "json" },
     | ^
> 10 |     { filename: "package-lock.json", type: "json" },
     | ^
> 11 |     // shell plugin will show version in bottom right corrner
     | ^
> 12 |     { filename: "app/shell-plugin/webapp/model/config.json", type: "json" }
     | ^
> 13 | ];
     | ^
> 14 |
     | ^
> 15 | // bump all package.json fiiles of ui5 apps
     | ^
> 16 | bumpFiles.push(
     | ^
> 17 |     ...glob.sync("app/*/package.json").map((f) => ({
     | ^
> 18 |         filename: f,
     | ^
> 19 |         type: "json"
     | ^
> 20 |     }))
     | ^
> 21 | );
     | ^
> 22 |
     | ^
> 23 | // bump all manifest.json fiiles of ui5 apps
     | ^
> 24 | bumpFiles.push(
     | ^
> 25 |     ...glob.sync("app/**/manifest.json").map((f) => ({
     | ^
> 26 |         filename: f,
     | ^
> 27 |         updater: "./tools/ui5-manifest-version-updater"
     | ^
> 28 |     }))
     | ^
> 29 | );
     | ^
> 30 |
     | ^
> 31 | module.exports = {
     | ^
> 32 |     bumpFiles
     | ^
> 33 | };
     | ^
> 34 |
     | ^
    at r (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\parser-yaml.js:1:1107)
    at Object.an [as parse] (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\parser-yaml.js:150:3774)
    at Object.parse (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\index.js:7515:23)      
    at coreFormat (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\index.js:8829:18)        
    at formatWithCursor2 (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\index.js:9021:18) 
    at C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\index.js:38183:12
    at Object.check (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\prettier\index.js:38202:9)      
    at check (C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\src\worker.js:19:21)
    at C:\Users\laegner\.nvm\versions\node\v18.12.1\bin\node_modules\pretty-parallel\node_modules\piscina\dist\src\worker.js:141:32

**Comment by larsilus** [comment]
Exception is in \parser-yaml.js, but we have a .js file?

**Comment by skrtheboss** [comment]
Hi @larsilus, i could not reproduce the issue, can you provide a reproduction somewhere?
